services:
  - type: web
    name: mental-health-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 --worker-class uvicorn.workers.UvicornWorker api:app"
    healthCheckPath: "/health"
    healthCheckIntervalSeconds: 30
    healthCheckInitialDelaySeconds: 10
    healthCheckTimeoutSeconds: 10
    healthCheckGracePeriodSeconds: 30
